spring.application.name=byteshop-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:byteshop-secret-key-muito-longa-para-seguranca-minima-256bits}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method